package com.centrer.backend.entity;

public enum NotificationType {
    APPOINTMENT_REQUEST,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REFUSED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    NEW_PATIENT
}
